// =============================================
// DOCUMENT DATA — Data sebenar dari folder Sop & Policy
// Hospital Serian
// =============================================
var docsData = [
    { id:1, name:'Policy Credentialing & Privileging Hospital Serian', category:'polisi-klinikal', catLabel:'Polisi Klinikal', version:'2023-2026', date:'2023', size:'8.7 MB', type:'pdf', uploader:'Pentadbiran', desc:'Polisi kelayakan dan keistimewaan klinikal untuk kakitangan perubatan Hospital Serian.', file:'Sop %26 Policy/01 Policy Credentialing and Priviledging Hospital Serian.pdf' },
    { id:2, name:'OSH Policy (Occupational Safety & Health)', category:'polisi-pentadbiran', catLabel:'Polisi Pentadbiran', version:'2023', date:'2023', size:'13.0 MB', type:'pdf', uploader:'Unit KKP', desc:'Polisi Keselamatan dan Kesihatan Pekerjaan Hospital Serian.', file:'Sop %26 Policy/02 OSH Policy 2023.pdf' },
    { id:3, name:'Polisi JKKP (Jawatankuasa Keselamatan & Kesihatan)', category:'polisi-pentadbiran', catLabel:'Polisi Pentadbiran', version:'2023-2026', date:'2023', size:'1.0 MB', type:'pdf', uploader:'Unit KKP', desc:'Polisi Jawatankuasa Keselamatan dan Kesihatan Pekerjaan.', file:'Sop %26 Policy/02 Polisi JKKP 2023-2026(2).pdf' },
    { id:4, name:'Policy Infection Control', category:'polisi-klinikal', catLabel:'Polisi Klinikal', version:'2023-2026', date:'2023', size:'18.3 MB', type:'pdf', uploader:'Unit Kawalan Jangkitan', desc:'Polisi kawalan jangkitan merangkumi prosedur pencegahan dan pelaporan.', file:'Sop %26 Policy/05 Policy inf. control 2023-2026(5) (1).pdf' },
    { id:5, name:'Patient & Family Rights Policy', category:'polisi-klinikal', catLabel:'Polisi Klinikal', version:'2023-2026', date:'2023', size:'30.5 MB', type:'pdf', uploader:'Pentadbiran', desc:'Polisi hak pesakit dan keluarga Hospital Serian.', file:'Sop %26 Policy/06 PT fmly Right policy 23-26.pdf' },
    { id:6, name:'AMRO Policy (Antimicrobial Resistance)', category:'polisi-klinikal', catLabel:'Polisi Klinikal', version:'2023-2026', date:'2023', size:'3.8 MB', type:'pdf', uploader:'Farmasi', desc:'Polisi rintangan antimikrob dan pengurusan antibiotik.', file:'Sop %26 Policy/07 Amro 23-2026.pdf' },
    { id:7, name:'Medical Operational Policy', category:'polisi-jabatan', catLabel:'Polisi Jabatan', version:'2023', date:'2023', size:'22.0 MB', type:'pdf', uploader:'Jabatan Perubatan', desc:'Polisi operasi jabatan perubatan Hospital Serian.', file:'Sop %26 Policy/09a Medical operationl Policy 2023.pdf' },
    { id:8, name:'Policy O&G (Obstetrics & Gynaecology)', category:'polisi-jabatan', catLabel:'Polisi Jabatan', version:'2023-2026', date:'2023', size:'25.4 MB', type:'pdf', uploader:'Jabatan O&G', desc:'Polisi operasi Jabatan Obstetrik dan Ginekologi.', file:'Sop %26 Policy/09c Policy O%26G.pdf' },
    { id:9, name:'Policy O&G (Versi DOCX)', category:'polisi-jabatan', catLabel:'Polisi Jabatan', version:'2023-2026', date:'2023', size:'1.2 MB', type:'docx', uploader:'Jabatan O&G', desc:'Versi Word polisi Jabatan O&G.', file:'Sop %26 Policy/09c Policy O%26G 2023-  FINAL.docx' },
    { id:10, name:'Psychiatry Operational Policy', category:'polisi-jabatan', catLabel:'Polisi Jabatan', version:'—', date:'2023', size:'16.4 MB', type:'pdf', uploader:'Jabatan Psikiatri', desc:'Polisi operasi unit Psikiatri Hospital Serian.', file:'Sop %26 Policy/09i PSY - Operational Policy.pdf' },
    { id:11, name:'Operating Suite Policy', category:'polisi-jabatan', catLabel:'Polisi Jabatan', version:'2023-2026', date:'2023', size:'4.1 MB', type:'pdf', uploader:'Jabatan Pembedahan', desc:'Polisi pengurusan dewan bedah Hospital Serian.', file:'Sop %26 Policy/11 operating suite 23-2026 (1).pdf' },
    { id:12, name:'Haemodialisis Operational Policy', category:'polisi-jabatan', catLabel:'Polisi Jabatan', version:'—', date:'2023', size:'1.7 MB', type:'pdf', uploader:'Unit Haemodialisis', desc:'Polisi operasi unit haemodialisis.', file:'Sop %26 Policy/13c HAEMODIALISIS.pdf' },
    { id:13, name:'Pathology & Blood Transfusion Dept Policy', category:'polisi-jabatan', catLabel:'Polisi Jabatan', version:'6', date:'2023', size:'8.8 MB', type:'pdf', uploader:'Jabatan Patologi', desc:'Polisi operasi am Jabatan Patologi dan Pemindahan Darah.', file:'Sop %26 Policy/15 16 General Operational Policy version 6 of Pathology and Blood Transfusion Department Hospital Serian.pdf' },
    { id:14, name:'Medical Social Worker Policy', category:'polisi-jabatan', catLabel:'Polisi Jabatan', version:'2023-2026', date:'2023', size:'6.6 MB', type:'pdf', uploader:'Unit MSW', desc:'Polisi operasi Pekerja Sosial Perubatan.', file:'Sop %26 Policy/17 H Medical social Worker 23-26.pdf' },
    { id:15, name:'Fisioterapi Operational Policy', category:'polisi-jabatan', catLabel:'Polisi Jabatan', version:'2022-2025', date:'2022', size:'3.4 MB', type:'pdf', uploader:'Unit Fisioterapi', desc:'Polisi operasi Unit Fisioterapi.', file:'Sop %26 Policy/17A Fisioterapi 22-25.pdf' },
    { id:16, name:'Occupational Therapy Policy', category:'polisi-jabatan', catLabel:'Polisi Jabatan', version:'2023-2026', date:'2023', size:'6.8 MB', type:'pdf', uploader:'Unit OT', desc:'Polisi operasi Unit Terapi Pekerjaan.', file:'Sop %26 Policy/17B Occ Therapy 2023-2026.pdf' },
    { id:17, name:'PPP Policy (Public-Private Partnership)', category:'polisi-pentadbiran', catLabel:'Polisi Pentadbiran', version:'—', date:'2023', size:'7.3 MB', type:'pdf', uploader:'Pentadbiran', desc:'Polisi Perkongsian Awam-Swasta Hospital Serian.', file:'Sop %26 Policy/25 PPP Policy.pdf' },
    { id:18, name:'Credentialing & Privileging (Versi DOCX)', category:'borang', catLabel:'Borang & Templat', version:'2023-2026', date:'2023', size:'154 KB', type:'docx', uploader:'Pentadbiran', desc:'Templat dokumen C&P dalam format Word.', file:'Sop %26 Policy/C%26P 23-2026.docx' },
    { id:19, name:'Infection Control Unit Operational Policy', category:'polisi-klinikal', catLabel:'Polisi Klinikal', version:'—', date:'2023', size:'14.7 MB', type:'pdf', uploader:'Unit Kawalan Jangkitan', desc:'Polisi operasi Unit Kawalan Jangkitan.', file:'Sop %26 Policy/INFECTION CONTROL UNIT OPERATIONAL POLICY.pdf' },
    { id:20, name:'Senarai Polisi Hospital Serian', category:'lain', catLabel:'Lain-lain', version:'—', date:'2023', size:'17 KB', type:'docx', uploader:'Pentadbiran', desc:'Senarai lengkap semua polisi Hospital Serian.', file:'Sop %26 Policy/LIST OF POLICY.docx' },
    { id:21, name:'Surat Lantikan JK Patient & Family Rights', category:'lain', catLabel:'Lain-lain', version:'—', date:'2023', size:'477 KB', type:'pdf', uploader:'Pentadbiran', desc:'Surat pelantikan ahli jawatankuasa hak pesakit dan keluarga.', file:'Sop %26 Policy/Lantikan Pt Family Right.pdf' },
    { id:22, name:'Medical Staff By-Laws (DOCX)', category:'bylaws', catLabel:'Undang-undang Kecil', version:'2023-2026', date:'2023', size:'293 KB', type:'doc', uploader:'Pentadbiran', desc:'Undang-undang kecil kakitangan perubatan (versi Word).', file:'Sop %26 Policy/MEDICAL STAFF BY-LAWS HOSPITAL SERIAN 2023-2026.doc' },
    { id:23, name:'Medical Staff By-Laws (Final PDF)', category:'bylaws', catLabel:'Undang-undang Kecil', version:'2023', date:'2023', size:'2.5 MB', type:'pdf', uploader:'Pentadbiran', desc:'Undang-undang kecil kakitangan perubatan (versi akhir).', file:'Sop %26 Policy/Medical Staff By laws 2023 Final.pdf' },
    { id:24, name:'Policy for Outbreak Management', category:'polisi-klinikal', catLabel:'Polisi Klinikal', version:'—', date:'2023', size:'1.5 MB', type:'pdf', uploader:'Unit Kawalan Jangkitan', desc:'Polisi pengurusan wabak dan insiden jangkitan.', file:'Sop %26 Policy/POLICY FOR OUTBREAK.pdf' },
    { id:25, name:'Policy of Reuse Disposable Items', category:'polisi-klinikal', catLabel:'Polisi Klinikal', version:'—', date:'2023', size:'4.3 MB', type:'pdf', uploader:'Pentadbiran', desc:'Polisi penggunaan semula barangan pakai buang.', file:'Sop %26 Policy/POLICY OF REUSE DISP.ITEM.pdf' },
    { id:26, name:'Polisi Jawatankuasa POCT', category:'polisi-klinikal', catLabel:'Polisi Klinikal', version:'2', date:'2023', size:'2.8 MB', type:'pdf', uploader:'Jabatan Patologi', desc:'Polisi ujian di tempat rawatan (Point-of-Care Testing).', file:'Sop %26 Policy/POLISI JAWATANKUASA POCT VERSI 2.pdf' },
    { id:27, name:'Policy Privilege Kluster SGH', category:'polisi-klinikal', catLabel:'Polisi Klinikal', version:'—', date:'2023', size:'1.1 MB', type:'pdf', uploader:'Pentadbiran', desc:'Polisi keistimewaan kluster Hospital Umum Sarawak.', file:'Sop %26 Policy/Policy Priviledge Kluster SGH.pdf' },
    { id:28, name:'Policy for Nursing in Hospital Serian', category:'polisi-jabatan', catLabel:'Polisi Jabatan', version:'2023', date:'20 Sep 2023', size:'222 KB', type:'docx', uploader:'Jabatan Kejururawatan', desc:'Polisi kejururawatan Hospital Serian.', file:'Sop %26 Policy/Policy for Nursing in Serian Hospital 20.9.2023.docx' },
    { id:29, name:'Service Standard Fisioterapi', category:'lain', catLabel:'Lain-lain', version:'—', date:'2023', size:'44 KB', type:'pptx', uploader:'Unit Fisioterapi', desc:'Pembentangan piawaian perkhidmatan Fisioterapi.', file:'Sop %26 Policy/srvce standard 17A.pptx' }
];
